### ISSUE TITLE
Throws exception, when using translated slash subcommands

### ISSUE THREAD

**Issue by zxcqirara** [Kotlin-Discord/kord-extensions#158] opened 2022-05-21 21:02 UTC
# Description

I registered slash **sub**command (eg `/remind list`), but when I used it, bot throwed exception (with translated slash commands works fine)

Exception log:
```
Exception in thread "DefaultDispatcher-worker-12" java.lang.IllegalStateException: Unknown subcommand: list
    at com.kotlindiscord.kord.extensions.commands.application.slash.SlashCommand.findCommand(SlashCommand.kt:211)
    at com.kotlindiscord.kord.extensions.commands.application.slash.SlashCommand.findCommand(SlashCommand.kt:198)
    at com.kotlindiscord.kord.extensions.commands.application.slash.EphemeralSlashCommand.call(EphemeralSlashCommand.kt:44)
    at com.kotlindiscord.kord.extensions.commands.application.DefaultApplicationCommandRegistry.handle$suspendImpl(DefaultApplicationCommandRegistry.kt:353)
    at com.kotlindiscord.kord.extensions.commands.application.DefaultApplicationCommandRegistry.handle(DefaultApplicationCommandRegistry.kt)
    at com.kotlindiscord.kord.extensions.ExtensibleBot$registerListeners$8.invokeSuspend(ExtensibleBot.kt:177)
    at com.kotlindiscord.kord.extensions.ExtensibleBot$registerListeners$8.invoke(ExtensibleBot.kt)
    at com.kotlindiscord.kord.extensions.ExtensibleBot$registerListeners$8.invoke(ExtensibleBot.kt)
    at com.kotlindiscord.kord.extensions.ExtensibleBot$registerListeners$suspendImpl$$inlined$on$default$17$1.invokeSuspend(ExtensibleBot.kt:243)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@3a3f17ec, Dispatchers.Default]
```

# Versions

* `kord-core` 0.8.0-M14
* `kord-extensions` 1.5.4-SNAPSHOT
* Gradle 7.4.2
* JDK 17.0.2
* Kotlin 1.6.20

# Code Examples

Not working cmd:
```kt
class Reminder : Extension() {
	override val name = "reminder"
	
	override suspend fun setup() {
		ephemeralSlashCommand {
			name = "extensions.reminder.commandName"
			description = "extensions.reminder.commandDescription"
		
			ephemeralSubCommand {
				name = "extensions.reminder.list.commandName"
				description = "extensions.reminder.list.commandDescription"
		
				action {
					// Smart code...
				}
			}
		}
	}
}
```

Working cmd:
```kt
class Info : Extension() {
	override val name = "info"

	override suspend fun setup() {
		publicSlashCommand {
			name = "extensions.info.commandName"
			description = "extensions.info.commandDescription"

			action {
				// Another smart code...
			}
		}
	}
}
```

strings.properties
```properties
extensions.info.commandName = about
extensions.info.commandDescription = Get some info about this server

extensions.reminder.commandName = remind
extensions.reminder.commandDescription = Remind system
extensions.reminder.list.commandName = list
extensions.reminder.list.commandDescription = Shows your reminds list
```

**Comment by gdude2002** [comment] 2022-05-22 14:19
Thanks for that - as this snapshot isn't quite ready for release, I'm taking the opportunity to overhaul how the modules are tested. Once I've done that, I'll get to this!

**Comment by gdude2002** [comment] 2022-06-18 12:35
I've had a look at this with my own translations. I am unable to reproduce this [with our simple test extension](https://github.com/Kord-Extensions/kord-extensions/blob/develop/test-bot/src/main/kotlin/com/kotlindiscord/kord/extensions/testbot/extensions/I18nTestExtension.kt).

It might be worth removing the spaces either sides of the `=` in your properties file, but honestly, I'm not sure how to repro this.

**Comment by DRSchlaubi** [comment] 2022-07-07 00:22
> I've had a look at this with my own translations. I am unable to reproduce this [with our simple test extension](https://github.com/Kord-Extensions/kord-extensions/blob/develop/test-bot/src/main/kotlin/com/kotlindiscord/kord/extensions/testbot/extensions/I18nTestExtension.kt).
> 
> It might be worth removing the spaces either sides of the `=` in your properties file, but honestly, I'm not sure how to repro this.

Your test extension doesn't translate sub command names.

The issue is that locally the bot knows the command as <translation key> but discord knows it as <translation>

Root commands don't have that issue, as they use IDs rather than names

**Comment by NyCodeGHG** [comment] 2022-07-07 00:31
The problem here is, the translation keys in the test bot are the same as the translation, so the issue does not happen here

**Comment by gdude2002** [comment] 2022-07-07 14:53
Your observations are correct with the default Discord client, but do not match what I observed while I was using the slash command localization build override that Discord supplies. This build override has now expired, however, so we're stuck for the moment.

**Comment by gdude2002** [comment] 2022-07-07 14:54
![image](https://user-images.githubusercontent.com/204153/177804529-64c51004-16ff-4750-a134-bed864ac2c1a.png)

Here's an image provided by a Chinese user during testing.

**Comment by DRSchlaubi** [comment] 2022-07-07 15:17
> Your observations are correct with the default Discord client, but do not match what I observed while I was using the slash command localization build override that Discord supplies. This build override has now expired, however, so we're stuck for the moment.

Your observations are still inaccurate, as Discord only sends the "default locale name" and your example shows the same key as value, whether they differ in other languages is irrelevant, try using the same bundle we used in #162

**Comment by gdude2002** [comment] 2022-07-07 16:13
I've merged the PR - is that the last thing this issue needs?

**Comment by DRSchlaubi** [comment] 2022-07-07 16:15
it should be

**Comment by gdude2002** [comment] 2022-07-07 16:15
Sounds good, then - feel free to drop a comment to reopen if needed!

**Closed as completed by gdude2002** 2022-07-07 16:15 UTC
