### ISSUE TITLE
Add a new converter type, 'Union Converter'

### ISSUE THREAD

**Issue by bosukas** [Kotlin-Discord/kord-extensions#20] opened 2021-01-18 17:34 UTC
# Summary

I think a new `Union Converter` would be useful for some people. The idea is that it will allow for different types of arguments in the same parameter

An example of what I'm talking about can be seen [here](https://discordpy.readthedocs.io/en/latest/ext/commands/commands.html#typing-union) in discord.py.

Here, they have a parameter called `what`, which can either be a `discord.TextChannel` or a `discord.Member`
```py
import typing

@bot.command()
async def union(ctx, what: typing.Union[discord.TextChannel, discord.Member]):
    await ctx.send(what)
```

# Current Behaviour

At the moment, there is no feature implemented to support this, however there are two workarounds that can be used, both of which have their pros and cons.

**Nested try-catch statements**
This looks messy. This will also require each different argument to have it's own Arguments object and will make the try-catch statement more messier as the amount of different arguments for the same parameter increases.
We would also have to create our own signature for this command

```kt
// try catch
class UserArgs: Arguments() {
    val arg by user("user")
}

class TimeZoneArgs: Arguments() {
    val arg by timeZone("time zone")
}


command {
    name = "example"
    
    action {
        try {
            with(parse(::TimeZoneArgs)) {
                // code for time zone
            }
        } catch(e: ParseException) {
            try {
                with(parse(::UserArgs)) {
                    // code for user
                }
            } catch(e: ParseException) {
                // failed to pass user and time zone
            }
        }
    }
}
```

**Optional Arguments**
This is a little better however there are still problems with this.
This will give you a User AND a TimeZone (if both arguments were valid) rather than a User OR TimeZone. This can lead to some unexpected results both for the user and the developer. 
We would also have to create our own signature for this command as well. 
```kt
// optional
class Args: Arguments() {
    val user by optionalUser("user")
    val timeZone by timeZone("time zone")
}

command {
    name = "example"
    
    action {
        with(parse(::Args)) {
            when {
                user != null -> {
                    // code for user
                }
                timeZone != null -> {
                    // code for timezone
                }
            }
        }
    }
}
```

# Preferred Behaviour

An idea of how this Union Converter would look is
```kt
// using varags
class Args: Arguments() {
    val arg: Any = union("displayName", timeZone("time zone"), user("user"))
}

// using collections
class Args: Arguments() {
    val arg: Any = union("displayName", listOf(timeZone("time zone"), user("user")))
}


command {
    name = "example"
    
    signature(::Args) // <displayName: TimeZone | User>
    
    action {
        with(parse(::Args)) {
            when(arg) {
                is TimeZone -> {
                    // code for time zone
                }
                is User -> {
                    // code for user
                }
            }
        }
    }
}
```
In the case of all of the converters failing to convert an argument, it should return a ParseException.

# Suggestions

This is a rough idea of how an implementation for this converter could look like
```kt
class UnionConverter(val converters: Collection<Converter<Any>>): CoalescingConverter<Any>() {

    override suspend fun parse(args: List<String>, context: CommandContext, bot: ExtensibleBot): Int {
        for(converter in converters) {
            try {
                when(converter) {
                    is MultiConverter<*> -> {
                        val result = converter.parse(args, context, bot)
                        this.parsed = converter.parsed
                        return result
                    }
                    is CoalescingConverter<*> -> {
                        val result = converter.parse(args, context, bot)
                        this.parsed = converter.parsed
                        return result
                    }
                    is SingleConverter<*> -> {
                        val arg = args.first()
                        val result = converter.parse(arg, context, bot)

                        if(result) {
                            this.parsed = converter.parsed
                        }
                        return 1
                    }
                }
            } catch (e: ParseException) {} // ignore error
        }
        throw ParseException("Could not parse argument")
    }
}
```
Although I don't see a use case for needing lists in unions, they can be supported. 

# Implications

~EDIT: After looking at the discord docs, I think this might be able to be implemented into slash commands as well (from my understanding).  
In the discord docs, they demonstrate a command where you can get the permissions for either a user or a role~
```json
{
    "name": "permissions",
    "description": "Get or edit permissions for a user or a role",
    "options": [
        {
            "name": "user",
            "description": "Get or edit permissions for a user",
            "type": 2 
        },
        {
            "name": "role",
            "description": "Get or edit permissions for a role",
            "type": 2
        }
    ]
}
```
~From this it seems like union arguments are possible unless I'm understanding wrong~
These are sub-commands, oops

Error messages for when all the converters failed to parse will have to be generic, as I don't see a clean way of presenting the different error messages from the converters.

While optional and default arguments can technically be used, they shouldn't be. This can lead to behaviour maybe unintentional. For example, 
```kt
class Args: Arguments() {
    val arg: Any = union("displayName", defaultingTimeZone("time zone", "UTC"), user("user"))
}
```
This will try to parse the argument with the timeZone converter, and if it fails to convert it will default to "UTC", which will mean it will never try to convert the argument using the user converter.

**Comment by gdude2002** [comment] 2021-01-28 15:38
I've added a very experimental union converter. Please give it a go and see what happens.

**Comment by gdude2002** [comment] 2021-02-05 12:40
How has this been working out for you?

**Comment by bosukas** [comment] 2021-02-06 21:38
> How has this been working out for you?

So far, its been working fine, I haven't ran into anything yet, although I've been a little busy these past couple of days, so I haven't played around with it too much.
I think the only thing would be generating a proper signature, maybe by joining the display names of the different converters together with '|', instead of having us write a type name for it.

**Comment by bosukas** [comment] 2021-02-07 20:04
> How has this been working out for you?

I've been playing around with it a bit more.
I think that it would make more sense that the converter should catch any error while converting and ignore it, and then if 'shouldThrow' is true, it would give an error saying it couldn't convert the argument into x, y or z. If 'shouldThrow' is false, then it should just return that 0, as it consumed 0 arguments. 
I think this would be better as if the converters contain a single converter and it couldn't convert, it will throw an error which will prevent it from converting anything else.

**Comment by gdude2002** [comment] 2021-02-08 12:34
Okay, I've made both sets of changes. In fact, if a converter throws, it'll simply try to move onto the next one if `shouldThrow` is `false` - I think that better matches the intended behaviour of this converter.

**Comment by gdude2002** [comment] 2021-03-14 11:17
It's been over a month since we last talked about this - how is it working for you?

**Comment by bosukas** [comment] 2021-03-21 17:50
Sorry for the slow response, I thought I already replied to this  - probably didn't send or something.
I'm happy with how the converter functions right now, If I have any more suggestions or improvements for it I'll let you know on the Discord server or reply to this issue (if your still keeping it open)

**Comment by gdude2002** [comment] 2021-03-21 17:51
Alright, good stuff - I'll close it for now, feel free to open another if needed

**Closed as completed by gdude2002** 2021-03-21 17:51 UTC
